# Copyright 2022 The SODA Authors.
# Copyright 2022 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This mounts the nfs volume claim into /mnt and continuously
# overwrites /mnt/index.html with the time and hostname of the pod.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kahu-nfs-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: nfs
  template:
    metadata:
      labels:
        provider: nfs
    spec:
      containers:
      - image: {{ .Values.metaService.image }}
        imagePullPolicy: IfNotPresent
        name: nfs-driver
        command: ["/usr/local/bin/nfsprovider"]
        args:
        - "-d"
        - "/data"
        volumeMounts:
          # name must match the volume name below
        - name: nfs
          mountPath: "{{ .Values.metaService.mountPath }}"
        - name: socket
          mountPath: "/tmp"
      - image: {{ .Values.providers.nfsProvider.image }}
        imagePullPolicy: IfNotPresent
        name: meta-service
        command: ["/usr/local/bin/metaservice"]
        args:
        - "-p"
        - "8181"
        - "-a"
        - "{{ .Values.providers.nfsProvider.metaServiceAddr }}"
        ports:
        - name: grpc
          containerPort: {{ .Values.providers.nfsProvider.nfsProviderPort }}
        volumeMounts:
          # name must match the volume name below
          - name: socket
            mountPath: "/tmp"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
      - name: socket
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kahu-nfs-provider
  labels:
    provider: nfs
spec:
  ports:
    - name: grpc
      port: 8181
  selector:
    provider: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1024Mi
  volumeName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.providers.nfsProvider.nfsServer }}
    path: "{{ .Values.providers.nfsProvider.path }}"
    #  mountOptions:
    #- nfsvers=4.2
